### ISSUE TITLE
[BUG] Crashes on start on Android 12

### ISSUE THREAD

**Issue by fabmazz** [Sav22999/common-voice-android#191]
I cannot start the app, using Android 12. Tried by cleaning cache (as suggested by the system) but it didn't work.

I don't have much more information because as soon as the app starts, it crashes, and it does so every time.

##### About OS*

_OS version:_ Android 12,  Samsung OneUI 4.1

_OS language (in English):_ Italian

##### About the app (CV Project)*

_App release:_ 2.4.0.3::FD-GH

_App language (in **English**):_ Italian

##### About you device

_Device RAM:_ `6GB`

_Device display size (in Inches):_ `6.5 inch`

(**Optional**, but recommended) _Device model (and brand):_ `Samsung A52s 5G`

_From what store have you installed the app?:_  F-Droid

_Are there installed Google Services on your device?_ Yes 

#### **Description bug** *

I cannot start the app

#### **How to reproduce the bug** *

1. Open the app
2. Crashes

#### Log file

Since the app crashes on start, I cannot create a log file

**Comment by TKr** [comment]
FDroid build 2.4.0.3
`java.lang.IllegalArgumentException: org.commonvoice.saverio: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
`

**Comment by Sav22999** [comment]
@TKr Thanks for the report. I've unsertood the issue and I'll fix asap (today I hope).

Sortu for the incovenience
